name: build

on:
  push:
    branches: [ main, certification, dev ]
  pull_request:
    branches: [ main, certification, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm audit
      continue-on-error: true
    - run: npm outdated
      continue-on-error: true
    - run: npm ci
    - run: npm run eslint --if-present
    - run: npm run lint --if-present
    - run: npm run package
    - run: npm test
      env:
        CI: true
